//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MetricsAnalyzers {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MetricsAnalyzers.Resources", typeof(Resources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cyclomatic Complexity does not follow metric rules..
        /// </summary>
        internal static string CyclomaticComplexityAnalyzerDescription {
            get {
                return ResourceManager.GetString("CyclomaticComplexityAnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cyclomatic Complexity of &apos;{0}&apos; is {1}..
        /// </summary>
        internal static string CyclomaticComplexityAnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("CyclomaticComplexityAnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cyclomatic Complexity does not follow metric rules..
        /// </summary>
        internal static string CyclomaticComplexityAnalyzerTitle {
            get {
                return ResourceManager.GetString("CyclomaticComplexityAnalyzerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lines of Code does not follow metric rules..
        /// </summary>
        internal static string LinesOfCodeAnalyzerDescription {
            get {
                return ResourceManager.GetString("LinesOfCodeAnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lines of Code of &apos;{0}&apos; is {1}..
        /// </summary>
        internal static string LinesOfCodeAnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("LinesOfCodeAnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lines of Code does not follow metric rules..
        /// </summary>
        internal static string LinesOfCodeAnalyzerTitle {
            get {
                return ResourceManager.GetString("LinesOfCodeAnalyzerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lines of comment does not follow metric rules..
        /// </summary>
        internal static string LinesOfCommentAnalyzerDescription {
            get {
                return ResourceManager.GetString("LinesOfCommentAnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lines of comment of &apos;{0}&apos; is {1}..
        /// </summary>
        internal static string LinesOfCommentAnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("LinesOfCommentAnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lines of comment does not follow metric rules..
        /// </summary>
        internal static string LinesOfCommentAnalyzerTitle {
            get {
                return ResourceManager.GetString("LinesOfCommentAnalyzerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maintainability Index does not follow metric rules..
        /// </summary>
        internal static string MaintainabilityIndexAnalyzerDescription {
            get {
                return ResourceManager.GetString("MaintainabilityIndexAnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maintainability Index of &apos;{0}&apos; is {1}..
        /// </summary>
        internal static string MaintainabilityIndexAnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("MaintainabilityIndexAnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maintainability Index does not follow metric rules..
        /// </summary>
        internal static string MaintainabilityIndexAnalyzerTitle {
            get {
                return ResourceManager.GetString("MaintainabilityIndexAnalyzerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of local variables does not follow metric rules..
        /// </summary>
        internal static string NumberOfLocalVariablesAnalyzerDescription {
            get {
                return ResourceManager.GetString("NumberOfLocalVariablesAnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of local variables of &apos;{0}&apos; is {1}..
        /// </summary>
        internal static string NumberOfLocalVariablesAnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("NumberOfLocalVariablesAnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of local variables does not follow metric rules..
        /// </summary>
        internal static string NumberOfLocalVariablesAnalyzerTitle {
            get {
                return ResourceManager.GetString("NumberOfLocalVariablesAnalyzerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of parameters does not follow metric rules..
        /// </summary>
        internal static string NumberOfParametersAnalyzerDescription {
            get {
                return ResourceManager.GetString("NumberOfParametersAnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of parameters of &apos;{0}&apos; is {1}..
        /// </summary>
        internal static string NumberOfParametersAnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("NumberOfParametersAnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of parameters does not follow metric rules..
        /// </summary>
        internal static string NumberOfParametersAnalyzerTitle {
            get {
                return ResourceManager.GetString("NumberOfParametersAnalyzerTitle", resourceCulture);
            }
        }
    }
}
